server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: quality_hub
  datasource:
    url: jdbc:mysql://localhost:3306/quality_hub
    username: root
    password: ca$hc0w
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
    -  classpath:mapper/**.xml
jwt:
  secret: S5TM-KUvSWSEpcV62FmFUwPFQQmVlTizROSa5T1X_K4
  expiration: 86400000 # 1day